
# ------------Indian Railway Container Movement Analysis--------------

**STEP 1:import all libarary**

In [45]:
# import library

import pandas as pd
import numpy as np
import os

**STEP 2: Load Raw Data**

In [46]:
# Movement Files

apm_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\raw\dummy_apm_gti_imp.csv"

bmct_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\raw\dummy_bmct_imp.csv"

nsdt_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\raw\dummy_nsdt_imp.csv"

nsft_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\raw\dummy_nsft_imp.csv"

nsict_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\raw\dummy_nsict_imp.csv"

nsigt_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\raw\dummy_nsigt_imp.csv"

# Station Master

station_master_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\raw\Stations_FOIS_with_division.csv"
# read all the files 



apm_df = pd.read_csv(apm_path)
bmct_df = pd.read_csv(bmct_path)
nsdt_df = pd.read_csv(nsdt_path)
nsft_df = pd.read_csv(nsft_path)
nsict_df = pd.read_csv(nsict_path)
nsigt_df = pd.read_csv(nsigt_path)

station_df = pd.read_csv(station_master_path)

**STEP 3: Basic Data Understanding**

In [47]:
# Store all movement datasets in a dictionary for easier analysis

movement_datasets = {
    "APM": apm_df,
    "BMCT": bmct_df,
    "NSDT": nsdt_df,
    "NSFT": nsft_df,
    "NSICT": nsict_df,
    "NSIGT": nsigt_df
}

In [48]:
# Preview the Datasets


for name, df in movement_datasets.items():

    print(name)
    display(df.head())

APM

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude
0,ABEU2601043,107063052,IMPORT,RAIL,JNPA,Gateway Terminals India (GTI),PORT OUT,12/2/2025 06:20,1,18.87029,73.00640
1,ABEU2601043,107063052,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,12/2/2025 12:56,2,18.99092,73.12000
2,ABEU2601043,107063052,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,12/2/2025 13:12,3,19.04000,73.11495
3,ABEU2601043,107063052,IMPORT,RAIL,NVRD,NAVADE ROAD Mumbai Railway Division,STATION CROSSED,12/2/2025 13:38,4,19.05239,73.10000
4,ABEU2601043,107063052,IMPORT,RAIL,DDCL,DOMVIVALI CONTROL CABIN Mumbai Railway Division,STATION CROSSED,12/2/2025 15:10,5,19.15260,73.09170

BMCT

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude
0,AAIU2002534,107887564,IMPORT,RAIL,JNPA,Bharat Mumbai Container Terminals (PSA),PORT OUT,12/25/2025 03:40,1,18.87029,73.00640
1,AAIU2002534,107887564,IMPORT,RAIL,JNPT,Jawahar Lal Nehru Port Mumbai Division,STATION CROSSED,12/26/2025 01:40,2,18.94590,72.99870
2,AAIU2002534,107887564,IMPORT,RAIL,JSLE,Jasaichirle Jn. Mumbai Division,STATION CROSSED,12/26/2025 03:33,3,19.15260,73.09170
3,AAIU2002534,107887564,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,12/26/2025 12:57,4,18.99092,73.12000
4,AAIU2002534,107887564,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,12/26/2025 14:24,5,19.04000,73.11495

NSDT

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude
0,CXDU1282636,108198795,IMPORT,RAIL,JNPA,Nhava Sheva Distribution Terminal (NSDT),PORT OUT,12/24/2025 04:15,1,18.87029,73.0064
1,CXDU1282636,108198795,IMPORT,RAIL,JNPA,Nhava Sheva Freeport Terminal (NSFT),PORT OUT,12/24/2025 15:00,2,18.87029,73.0064
2,CXDU1282636,108198795,IMPORT,RAIL,JSLE,Jasaichirle Jn. Mumbai Division,STATION CROSSED,12/25/2025 07:49,3,19.15260,73.0917
3,CXDU1282636,108198795,IMPORT,RAIL,DPLI,DAPOLI Mumbai Railway Division,STATION CROSSED,12/25/2025 08:31,4,17.74310,73.2378
4,CXDU1282636,108198795,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,12/25/2025 09:12,5,18.99092,73.1200

NSFT

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude
0,AMHU8001163,108052652,IMPORT,RAIL,JNPA,Nhava Sheva Freeport Terminal (NSFT),PORT OUT,12/22/2025 04:04,1,18.87029,73.0064
1,AMHU8001163,108052652,IMPORT,RAIL,ICDG,INLAND CONTAINER DEPOT AT JUHI/KANPUR Allahaba...,STATION CROSSED,1/11/2026 07:25,2,26.44990,80.2976
2,AMHU8001163,108052652,IMPORT,RAIL,BPUN,NEW BHAUPUR JN.,STATION CROSSED,1/11/2026 13:00,3,26.44990,80.2976
3,AMHU8001163,108052652,IMPORT,RAIL,KNSD,NEW KANCHAUSI,STATION CROSSED,1/11/2026 13:44,4,26.75950,79.8920
4,AMHU8001163,108052652,IMPORT,RAIL,ULDN,NEW ACHALDA,STATION CROSSED,1/11/2026 14:08,5,25.96040,74.8401

NSICT

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude
0,ABEU2632392,107062215,IMPORT,RAIL,JNPA,Nhava Sheva International Container Terminal (...,PORT OUT,11/30/2025 05:01,1,18.87029,73.0064
1,ABEU2632392,107062215,IMPORT,RAIL,JNPA,Gateway Terminals India (GTI),PORT OUT,11/30/2025 11:20,2,18.87029,73.0064
2,ABEU2632392,107062215,IMPORT,RAIL,CMLK,M/S GREENFIELD PFT OF CONCOR NEEMRANA SERVED B...,STATION CROSSED,12/6/2025 22:47,3,28.13710,76.3471
3,ABEU2632392,107062215,IMPORT,RAIL,REJN,NEW REWARI,STATION CROSSED,12/6/2025 23:14,4,28.19840,76.6192
4,ABEU2632392,107062215,IMPORT,RAIL,TKDC,TUGLAKABAD CABIN Delhi Railway Division,STATION CROSSED,12/7/2025 07:08,5,28.46000,77.3000

NSIGT

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude
0,AMFU3171760,107860264,IMPORT,RAIL,JNPA,Nhava Sheva India Gateway Terminal (NSIGT),PORT OUT,12/23/2025 01:34,1,18.87029,73.0064
1,AMFU3171760,107860264,IMPORT,RAIL,JNPT,Jawahar Lal Nehru Port Mumbai Division,STATION CROSSED,12/23/2025 10:01,2,18.94590,72.9987
2,AMFU3171760,107860264,IMPORT,RAIL,JSLE,Jasaichirle Jn. Mumbai Division,STATION CROSSED,12/25/2025 03:01,3,19.15260,73.0917
3,AMFU3171760,107860264,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,12/25/2025 05:19,4,18.99092,73.1200
4,AMFU3171760,107860264,IMPORT,RAIL,DDCL,DOMVIVALI CONTROL CABIN Mumbai Railway Division,STATION CROSSED,12/25/2025 12:30,5,19.15260,73.0917

In [49]:

# Dataset Information


for name, df in movement_datasets.items():

    print("=" * 80)
    print(name)
    print("=" * 80)

    df.info()

================================================================================
APM
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 173150 entries, 0 to 173149
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   cntr_no           173150 non-null  str
 1   cntr_trxn_id      173150 non-null  int64
 2   category          173150 non-null  str
 3   transport_mode    173150 non-null  str
 4   location_code     173150 non-null  str
 5   location_name     173150 non-null  str
 6   event_name        173150 non-null  str
 7   event_time        173150 non-null  str
 8   station_sequence  173150 non-null  int64
 9   Latitude          173150 non-null  float64
 10  Longitude         173150 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 29.0 MB
================================================================================
BMCT
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 323538 entries, 0 to 323537
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   cntr_no           323538 non-null  str
 1   cntr_trxn_id      323538 non-null  int64
 2   category          323538 non-null  str
 3   transport_mode    323538 non-null  str
 4   location_code     323538 non-null  str
 5   location_name     323538 non-null  str
 6   event_name        323538 non-null  str
 7   event_time        323538 non-null  str
 8   station_sequence  323538 non-null  int64
 9   Latitude          323538 non-null  float64
 10  Longitude         323538 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 54.4 MB
================================================================================
NSDT
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cntr_no           57 non-null     str
 1   cntr_trxn_id      57 non-null     int64
 2   category          57 non-null     str
 3   transport_mode    57 non-null     str
 4   location_code     57 non-null     str
 5   location_name     57 non-null     str
 6   event_name        57 non-null     str
 7   event_time        57 non-null     str
 8   station_sequence  57 non-null     int64
 9   Latitude          57 non-null     float64
 10  Longitude         57 non-null     float64
dtypes: float64(2), int64(2), str(7)
memory usage: 10.1 KB
================================================================================
NSFT
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 77805 entries, 0 to 77804
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cntr_no           77805 non-null  str
 1   cntr_trxn_id      77805 non-null  int64
 2   category          77805 non-null  str
 3   transport_mode    77805 non-null  str
 4   location_code     77805 non-null  str
 5   location_name     77805 non-null  str
 6   event_name        77805 non-null  str
 7   event_time        77805 non-null  str
 8   station_sequence  77805 non-null  int64
 9   Latitude          77805 non-null  float64
 10  Longitude         77805 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 13.0 MB
================================================================================
NSICT
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 132521 entries, 0 to 132520
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   cntr_no           132521 non-null  str
 1   cntr_trxn_id      132521 non-null  int64
 2   category          132521 non-null  str
 3   transport_mode    132521 non-null  str
 4   location_code     132521 non-null  str
 5   location_name     132521 non-null  str
 6   event_name        132521 non-null  str
 7   event_time        132521 non-null  str
 8   station_sequence  132521 non-null  int64
 9   Latitude          132521 non-null  float64
 10  Longitude         132521 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 22.3 MB
================================================================================
NSIGT
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 90059 entries, 0 to 90058
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cntr_no           90059 non-null  str
 1   cntr_trxn_id      90059 non-null  int64
 2   category          90059 non-null  str
 3   transport_mode    90059 non-null  str
 4   location_code     90059 non-null  str
 5   location_name     90059 non-null  str
 6   event_name        90059 non-null  str
 7   event_time        90059 non-null  str
 8   station_sequence  90059 non-null  int64
 9   Latitude          90059 non-null  float64
 10  Longitude         90059 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 15.1 MB

1.No missing data is there in dataset\
2.Event time is currently stored as a text field and will be converted to datetime during preprocessing.

In [50]:
# statical analysis of daataset
for name, df in movement_datasets.items():

    print("=" * 20)
    print(name)
    print("=" * 20)

    display(df.describe())

====================
APM
====================

       cntr_trxn_id  station_sequence       Latitude      Longitude
count  1.731500e+05     173150.000000  173150.000000  173150.000000
mean   1.075208e+08         23.651285      20.626954      74.546750
std    3.547398e+05         20.521174       2.540637       2.020876
min    1.042041e+08          1.000000      12.971600      69.719100
25%    1.072297e+08          7.000000      19.040000      73.091700
50%    1.074949e+08         17.000000      19.817370      73.672010
75%    1.077933e+08         36.000000      21.160000      75.830000
max    1.082627e+08        136.000000      31.634000      88.390000

====================
BMCT
====================

       cntr_trxn_id  station_sequence       Latitude      Longitude
count  3.235380e+05     323538.000000  323538.000000  323538.000000
mean   1.074556e+08         26.763561      20.564551      74.651491
std    3.470192e+05         22.122539       2.154184       2.028697
min    1.066116e+08          1.000000      12.971600      69.719100
25%    1.071683e+08          8.000000      19.152600      73.091700
50%    1.074172e+08         21.000000      20.250000      73.840000
75%    1.076994e+08         41.000000      21.050000      75.880000
max    1.082816e+08        136.000000      31.634000      88.390000

====================
NSDT
====================

       cntr_trxn_id  station_sequence  Latitude  Longitude
count  5.700000e+01         57.000000  57.00000  57.000000
mean   1.078812e+08          7.649123  19.17909  72.966156
std    3.042304e+05          4.181128   0.51166   0.156668
min    1.075923e+08          1.000000  17.74310  72.743370
25%    1.075923e+08          4.000000  18.99092  72.810000
50%    1.075981e+08          8.000000  19.15260  73.006400
75%    1.081988e+08         11.000000  19.45000  73.091700
max    1.081994e+08         15.000000  19.99000  73.237800

====================
NSFT
====================

       cntr_trxn_id  station_sequence      Latitude     Longitude
count  7.780500e+04      77805.000000  77805.000000  77805.000000
mean   1.074797e+08         25.849457     20.487096     74.700774
std    3.381606e+05         21.510461      2.796360      2.050670
min    1.066559e+08          1.000000     12.560850     69.690910
25%    1.072359e+08          9.000000     18.870290     73.110000
50%    1.074441e+08         20.000000     19.700000     73.920000
75%    1.077580e+08         38.000000     21.240000     75.930000
max    1.082297e+08        135.000000     31.634000     88.390000

====================
NSICT
====================

       cntr_trxn_id  station_sequence       Latitude      Longitude
count  1.325210e+05     132521.000000  132521.000000  132521.000000
mean   1.075596e+08         23.573992      20.410715      74.372296
std    3.948880e+05         19.144448       2.543307       1.731751
min    1.066158e+08          1.000000      12.971600      69.719100
25%    1.072131e+08          8.000000      18.990920      73.091700
50%    1.075180e+08         18.000000      19.780000      73.635940
75%    1.078356e+08         35.000000      21.130000      75.417120
max    1.082884e+08        135.000000      31.634000      88.390000

====================
NSIGT
====================

       cntr_trxn_id  station_sequence      Latitude     Longitude
count  9.005900e+04      90059.000000  90059.000000  90059.000000
mean   1.075709e+08         27.831188     19.398632     74.523231
std    3.296553e+05         24.263099      2.284789      1.769493
min    1.065610e+08          1.000000     12.560850     69.719100
25%    1.072771e+08          8.000000     18.470000     73.091700
50%    1.075661e+08         20.000000     19.152600     73.832800
75%    1.077916e+08         44.000000     20.730000     75.710000
max    1.082659e+08        102.000000     30.910000     88.271400

In [51]:
# Schema Validation
for name, df in movement_datasets.items():

    print(name)
    print(df.columns.tolist())

APM
['cntr_no', 'cntr_trxn_id', 'category', 'transport_mode', 'location_code', 'location_name', 'event_name', 'event_time', 'station_sequence', 'Latitude', 'Longitude']
BMCT
['cntr_no', 'cntr_trxn_id', 'category', 'transport_mode', 'location_code', 'location_name', 'event_name', 'event_time', 'station_sequence', 'Latitude', 'Longitude']
NSDT
['cntr_no', 'cntr_trxn_id', 'category', 'transport_mode', 'location_code', 'location_name', 'event_name', 'event_time', 'station_sequence', 'Latitude', 'Longitude']
NSFT
['cntr_no', 'cntr_trxn_id', 'category', 'transport_mode', 'location_code', 'location_name', 'event_name', 'event_time', 'station_sequence', 'Latitude', 'Longitude']
NSICT
['cntr_no', 'cntr_trxn_id', 'category', 'transport_mode', 'location_code', 'location_name', 'event_name', 'event_time', 'station_sequence', 'Latitude', 'Longitude']
NSIGT
['cntr_no', 'cntr_trxn_id', 'category', 'transport_mode', 'location_code', 'location_name', 'event_name', 'event_time', 'station_sequence', 'Latitude', 'Longitude']

**Step 4: Data Quality Validation**

In [52]:
# Missing Value Analysis

for name, df in movement_datasets.items():
    
    print(name)
    print(df.isnull().sum().sum())

APM
0
BMCT
0
NSDT
0
NSFT
0
NSICT
0
NSIGT
0

In [53]:
# STEP Duplicate Record Analysis

for name, df in movement_datasets.items():

    print(name)
    print("Duplicate Rows :", df.duplicated().sum())

APM
Duplicate Rows : 0
BMCT
Duplicate Rows : 0
NSDT
Duplicate Rows : 0
NSFT
Duplicate Rows : 0
NSICT
Duplicate Rows : 0
NSIGT
Duplicate Rows : 0

In [54]:
# Category validation
for name, df in movement_datasets.items():
    print(name)
    print("="*80)
    print(df["category"].value_counts())

APM
================================================================================
category
IMPORT    173150
Name: count, dtype: int64
BMCT
================================================================================
category
IMPORT    323538
Name: count, dtype: int64
NSDT
================================================================================
category
IMPORT    57
Name: count, dtype: int64
NSFT
================================================================================
category
IMPORT    77805
Name: count, dtype: int64
NSICT
================================================================================
category
IMPORT    132521
Name: count, dtype: int64
NSIGT
================================================================================
category
IMPORT    90059
Name: count, dtype: int64

In [55]:

# Transport Mode Validation
for name, df in movement_datasets.items():

    print(name)
    print("=" * 80)
    print(df["transport_mode"].value_counts(), "\n")

APM
================================================================================
transport_mode
RAIL    173150
Name: count, dtype: int64

BMCT
================================================================================
transport_mode
RAIL    323538
Name: count, dtype: int64

NSDT
================================================================================
transport_mode
RAIL    57
Name: count, dtype: int64

NSFT
================================================================================
transport_mode
RAIL    77805
Name: count, dtype: int64

NSICT
================================================================================
transport_mode
RAIL    132521
Name: count, dtype: int64

NSIGT
================================================================================
transport_mode
RAIL    90059
Name: count, dtype: int64

In [56]:

# Event Name Validation

for name, df in movement_datasets.items():

    print("=" * 80)
    print(name)
    print("=" * 80)

    print(df["event_name"].value_counts(), "\n")

================================================================================
APM
================================================================================
event_name
STATION CROSSED    166129
PORT OUT             7021
Name: count, dtype: int64

================================================================================
BMCT
================================================================================
event_name
STATION CROSSED    312955
PORT OUT            10583
Name: count, dtype: int64

================================================================================
NSDT
================================================================================
event_name
STATION CROSSED    49
PORT OUT            8
Name: count, dtype: int64

================================================================================
NSFT
================================================================================
event_name
STATION CROSSED    75281
PORT OUT            2524
Name: count, dtype: int64

================================================================================
NSICT
================================================================================
event_name
STATION CROSSED    127958
PORT OUT             4563
Name: count, dtype: int64

================================================================================
NSIGT
================================================================================
event_name
STATION CROSSED    87014
PORT OUT            3045
Name: count, dtype: int64

In [57]:

# STEP 4.6 : Event Time Range

for name, df in movement_datasets.items():

    print(name)
    print("=" * 80)

    df["event_time"] = pd.to_datetime(df["event_time"])
    print("From :", df["event_time"].min())
    print("To   :", df["event_time"].max(), "\n")

APM
================================================================================
From : 2025-11-24 02:21:00
To   : 2026-01-30 22:13:00

BMCT
================================================================================
From : 2025-11-24 07:04:00
To   : 2026-01-30 13:43:00

NSDT
================================================================================
From : 2025-12-11 04:25:00
To   : 2025-12-27 12:00:00

NSFT
================================================================================
From : 2025-11-23 00:38:00
To   : 2026-01-30 15:09:00

NSICT
================================================================================
From : 2025-11-24 22:59:00
To   : 2026-01-30 11:35:00

NSIGT
================================================================================
From : 2025-11-24 07:20:00
To   : 2026-01-27 19:54:00

In [58]:

# STEP 4.7 : Station Sequence Validation


for name, df in movement_datasets.items():
    print(name)
    print("=" * 80)

    print(f"Minimum Station Sequence : {df['station_sequence'].min()}")
    print(f"Maximum Station Sequence : {df['station_sequence'].max()}\n")

APM
================================================================================
Minimum Station Sequence : 1
Maximum Station Sequence : 136

BMCT
================================================================================
Minimum Station Sequence : 1
Maximum Station Sequence : 136

NSDT
================================================================================
Minimum Station Sequence : 1
Maximum Station Sequence : 15

NSFT
================================================================================
Minimum Station Sequence : 1
Maximum Station Sequence : 135

NSICT
================================================================================
Minimum Station Sequence : 1
Maximum Station Sequence : 135

NSIGT
================================================================================
Minimum Station Sequence : 1
Maximum Station Sequence : 102

In [59]:

#  Container Number Validation

for name, df in movement_datasets.items():
    print(name)
    print("=" * 80)
    print(df.groupby("cntr_no")["cntr_trxn_id"].nunique().value_counts())

APM
================================================================================
cntr_trxn_id
1    6692
2       1
Name: count, dtype: int64
BMCT
================================================================================
cntr_trxn_id
1    10527
2        1
Name: count, dtype: int64
NSDT
================================================================================
cntr_trxn_id
1    4
Name: count, dtype: int64
NSFT
================================================================================
cntr_trxn_id
1    2435
2       3
Name: count, dtype: int64
NSICT
================================================================================
cntr_trxn_id
1    4332
2       1
Name: count, dtype: int64
NSIGT
================================================================================
cntr_trxn_id
1    3043
2       1
Name: count, dtype: int64


Most containers are associated with a single transaction.\
A small number of containers are linked to multiple transactions.\
Therefore, cntr_no alone cannot uniquely identify a journey.

In [60]:
# transcation id validation 
for name , df in movement_datasets.items():
    print(name)
    print("="*80)
    print(df.groupby("cntr_trxn_id")["cntr_no"].nunique().value_counts())

APM
================================================================================
cntr_no
1    6634
2      30
Name: count, dtype: int64
BMCT
================================================================================
cntr_no
1    10391
2       69
Name: count, dtype: int64
NSDT
================================================================================
cntr_no
1    4
Name: count, dtype: int64
NSFT
================================================================================
cntr_no
1    2431
2       5
Name: count, dtype: int64
NSICT
================================================================================
cntr_no
1    4302
2      16
Name: count, dtype: int64
NSIGT
================================================================================
cntr_no
1    3016
2      13
3       1
Name: count, dtype: int64

Most transaction IDs belong to a single container.\
However, a few transaction IDs are associated with multiple containers.\
Therefore, cntr_trxn_id alone cannot uniquely identify a journey.

In [61]:

#  PORT OUT Validation

for name, df in movement_datasets.items():

    print("=" * 80)
    print(name)
    print("=" * 80)

    port_out = df[df["event_name"] == "PORT OUT"]

    print(
        port_out
        .groupby(["cntr_no", "cntr_trxn_id"])
        .size()
        .value_counts()
    )

================================================================================
APM
================================================================================
1    6369
2     323
3       2
Name: count, dtype: int64
================================================================================
BMCT
================================================================================
1    10475
2       54
Name: count, dtype: int64
================================================================================
NSDT
================================================================================
2    4
Name: count, dtype: int64
================================================================================
NSFT
================================================================================
1    2359
2      81
3       1
Name: count, dtype: int64
================================================================================
NSICT
================================================================================
1    4106
2     227
3       1
Name: count, dtype: int64
================================================================================
NSIGT
================================================================================
1    3045
Name: count, dtype: int64


 Overall Observation - Data Quality Validation


• No missing values or duplicate records were identified across the movement datasets.\
• Category, transport mode, and event names are consistent throughout the data.\
• Event timestamps were successfully validated and are suitable for datetime conversion.\
• Station sequence values indicate the chronological order of container movements.\
• Business key validation revealed that neither cntr_no nor cntr_trxn_id alone uniquely identifies a journey.\
• A small number of records contain multiple PORT OUT events; therefore, as per the assignment guidelines, the PORT OUT event with  station_sequence = 1 will be considered the definitive origin.\
• Based on these validations, the data is suitable for preprocessing and OD pair construction.

**STEP 5 : Data Preprocessing**

In [62]:

#  Add Terminal Identifier


apm_df["terminal"] = "GTI"
bmct_df["terminal"] = "BMCT"
nsdt_df["terminal"] = "NSDT"
nsft_df["terminal"] = "NSFT"
nsict_df["terminal"] = "NSICT"
nsigt_df["terminal"] = "NSIGT"

In [63]:
print(apm_df.head(5))

       cntr_no  cntr_trxn_id category transport_mode location_code  \
0  ABEU2601043     107063052   IMPORT           RAIL          JNPA
1  ABEU2601043     107063052   IMPORT           RAIL          PNVL
2  ABEU2601043     107063052   IMPORT           RAIL          KLMG
3  ABEU2601043     107063052   IMPORT           RAIL          NVRD
4  ABEU2601043     107063052   IMPORT           RAIL          DDCL

                                     location_name       event_name  \
0                    Gateway Terminals India (GTI)         PORT OUT
1                       Panvel Jn. Mumbai Division  STATION CROSSED
2          KALAMBOLI GOODS Mumbai Railway Division  STATION CROSSED
3              NAVADE ROAD Mumbai Railway Division  STATION CROSSED
4  DOMVIVALI CONTROL CABIN Mumbai Railway Division  STATION CROSSED

           event_time  station_sequence  Latitude  Longitude terminal
0 2025-12-02 06:20:00                 1  18.87029   73.00640      GTI
1 2025-12-02 12:56:00                 2  18.99092   73.12000      GTI
2 2025-12-02 13:12:00                 3  19.04000   73.11495      GTI
3 2025-12-02 13:38:00                 4  19.05239   73.10000      GTI
4 2025-12-02 15:10:00                 5  19.15260   73.09170      GTI

In [64]:
bmct_df.head(5)

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal
0,AAIU2002534,107887564,IMPORT,RAIL,JNPA,Bharat Mumbai Container Terminals (PSA),PORT OUT,2025-12-25 03:40:00,1,18.87029,73.00640,BMCT
1,AAIU2002534,107887564,IMPORT,RAIL,JNPT,Jawahar Lal Nehru Port Mumbai Division,STATION CROSSED,2025-12-26 01:40:00,2,18.94590,72.99870,BMCT
2,AAIU2002534,107887564,IMPORT,RAIL,JSLE,Jasaichirle Jn. Mumbai Division,STATION CROSSED,2025-12-26 03:33:00,3,19.15260,73.09170,BMCT
3,AAIU2002534,107887564,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-26 12:57:00,4,18.99092,73.12000,BMCT
4,AAIU2002534,107887564,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-26 14:24:00,5,19.04000,73.11495,BMCT

In [129]:

# Append All Movement Files

movement_df = pd.concat(
    [
        apm_df,
        bmct_df,
        nsdt_df,
        nsft_df,
        nsict_df,
        nsigt_df
    ],
    ignore_index=True
)

In [66]:
movement_df.head(5)

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal
0,ABEU2601043,107063052,IMPORT,RAIL,JNPA,Gateway Terminals India (GTI),PORT OUT,2025-12-02 06:20:00,1,18.87029,73.00640,GTI
1,ABEU2601043,107063052,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-02 12:56:00,2,18.99092,73.12000,GTI
2,ABEU2601043,107063052,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-02 13:12:00,3,19.04000,73.11495,GTI
3,ABEU2601043,107063052,IMPORT,RAIL,NVRD,NAVADE ROAD Mumbai Railway Division,STATION CROSSED,2025-12-02 13:38:00,4,19.05239,73.10000,GTI
4,ABEU2601043,107063052,IMPORT,RAIL,DDCL,DOMVIVALI CONTROL CABIN Mumbai Railway Division,STATION CROSSED,2025-12-02 15:10:00,5,19.15260,73.09170,GTI

In [67]:
print("Movement Dataset Shape :", movement_df.shape)

Movement Dataset Shape : (797130, 12)

In [68]:

# Convert Event Time to DateTime

movement_df["event_time"] = pd.to_datetime(movement_df["event_time"])

In [69]:
movement_df.dtypes

cntr_no                        str
cntr_trxn_id                 int64
category                       str
transport_mode                 str
location_code                  str
location_name                  str
event_name                     str
event_time          datetime64[us]
station_sequence             int64
Latitude                   float64
Longitude                  float64
terminal                       str
dtype: object

In [70]:

#  Create Journey Key

movement_df["journey_key"] = (
    movement_df["cntr_no"].astype(str) + "_" + movement_df["cntr_trxn_id"].astype(str))

In [71]:

# STEP 5.4 : Extract Date Features


movement_df["event_date"] = movement_df["event_time"].dt.date

movement_df["event_hour"] = movement_df["event_time"].dt.hour

movement_df["day_of_week"] = movement_df["event_time"].dt.day_name()

movement_df["week_number"] = movement_df["event_time"].dt.isocalendar().week

In [72]:
movement_df.head(5)

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal,journey_key,event_date,event_hour,day_of_week,week_number
0,ABEU2601043,107063052,IMPORT,RAIL,JNPA,Gateway Terminals India (GTI),PORT OUT,2025-12-02 06:20:00,1,18.87029,73.00640,GTI,ABEU2601043_107063052,2025-12-02,6,Tuesday,49
1,ABEU2601043,107063052,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-02 12:56:00,2,18.99092,73.12000,GTI,ABEU2601043_107063052,2025-12-02,12,Tuesday,49
2,ABEU2601043,107063052,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-02 13:12:00,3,19.04000,73.11495,GTI,ABEU2601043_107063052,2025-12-02,13,Tuesday,49
3,ABEU2601043,107063052,IMPORT,RAIL,NVRD,NAVADE ROAD Mumbai Railway Division,STATION CROSSED,2025-12-02 13:38:00,4,19.05239,73.10000,GTI,ABEU2601043_107063052,2025-12-02,13,Tuesday,49
4,ABEU2601043,107063052,IMPORT,RAIL,DDCL,DOMVIVALI CONTROL CABIN Mumbai Railway Division,STATION CROSSED,2025-12-02 15:10:00,5,19.15260,73.09170,GTI,ABEU2601043_107063052,2025-12-02,15,Tuesday,49

**STEP 6 : Station Master Validation**

In [73]:

# Preview Station Master

station_df.head()

,Location Code,Location Name,Station Name,Division,Division (Normalized),Latitude,Longitude,Location Code.1,Latitude.1,Longitude.1
0,ASGN,AARTI STEELS LTD SDG,AARTI STEELS LTD SDG,Khurda Road Division,Khurda Road Division,21.1900,81.2900,ASGN,21.1900,81.2900
1,ABB,ABADA,ABADA,Kharagpur Division,Kharagpur Division,22.5500,88.2000,ABB,22.5500,88.2000
2,ABR,ABU ROAD Ajmer Railway Division,ABU ROAD,Ajmer Railway Division,Ajmer Division,24.4700,72.7800,ABR,24.4700,72.7800
3,ACG,ACHEGAON Bhusawal Railway Division,ACHEGAON,Bhusawal Division,Bhusawal Division,20.9762,75.9342,ACG,20.9762,75.9342
4,AH,ACHHNERA JN. Agra Railway Division,ACHHNERA JN.,Agra Railway Division,Agra Division,27.1800,77.7600,AH,27.1800,77.7600

In [74]:
# checking shape of station

print("Station Master Shape :", station_df.shape)

Station Master Shape : (1983, 10)

In [75]:
# checking null value 
station_df.isnull().sum()

Location Code            0
Location Name            0
Station Name             0
Division                 0
Division (Normalized)    0
Latitude                 0
Longitude                0
Location Code.1          0
Latitude.1               0
Longitude.1              0
dtype: int64

In [76]:
# cheking duplicates
print("Duplicate Location Codes :",station_df["Location Code"].duplicated().sum())

Duplicate Location Codes : 22

In [77]:
station_df[station_df["Location Code"].duplicated()]

,Location Code,Location Name,Station Name,Division,Division (Normalized),Latitude,Longitude,Location Code.1,Latitude.1,Longitude.1
8,Port,Adani Gangavaram Port,Adani Gangavaram Port,Gangavaram Port,Gangavaram Port,17.6600,83.2000,Gangavaram,17.6600,83.2000
9,Port,Adani International Container Terminal (AICTPL),Adani International Container Terminal (AICTPL),Mundra Port,Mundra Port,22.7382,69.7065,Mundra,22.7382,69.7065
11,Port,Adani Mundra Container Terminal (AMCT),Adani Mundra Container Terminal (AMCT),Mundra Port,Mundra Port,22.7382,69.7065,Mundra,22.7382,69.7065
12,Port,Adani Mundra Container Terminal 2,Adani Mundra Container Terminal 2,Mundra Port,Mundra Port,22.7382,69.7065,Mundra,22.7382,69.7065
237,Port,Bharat Mumbai Container Terminals (PSA),Bharat Mumbai Container Terminals (PSA),JNPA Port,JNPA Port,18.9186,72.9692,JNPA,18.9186,72.9692
356,Port,Chennai Container Terminal Pvt. Ltd. (CCTL),CCTL CHENNAI,Chennai Port,Chennai Division,13.0827,80.2707,Chennai,13.0827,80.2707
357,Port,Chennai International Terminals Pvt Ltd (CITPL),Chennai International Terminals Pvt Ltd (CITPL),Chennai Port,Chennai Port,13.0500,80.1800,Chennai,13.0500,80.1800
400,Port,Customs (South Basin) Gate Mundra,Customs (South Basin) Gate Mundra,Mundra Port,Mundra Port,22.7382,69.7065,Mundra,22.7382,69.7065
584,Port,Gateway Terminals India (GTI),Gateway Terminals India (GTI),JNPA Port,JNPA Port,18.9186,72.9692,JNPA,18.9186,72.9692
652,Port,Haldia International Container Terminal (HICT),Haldia International Container Terminal (HICT),Haldia Port,Haldia Port,22.0400,88.0900,Haldia,22.0400,88.0900
717,Port,International Container Transhipment Terminal ...,ICTT KOCHI,Kochi Port,Kochi Port,9.9312,76.2673,Kochi,9.9312,76.2673
845,Port,Kandla International Container Terminal (KICT),KICT KANDLA,Kandla Port,Kandla Port,23.0733,70.2167,Kandla,23.0733,70.2167
1152,Port,Marine Infrastructure Developer Private Limited,MARINE INFRA (approx),Kattupalli Port,Kattupalli Port,15.0000,74.0000,Kattupalli,15.0000,74.0000
1211,Port,Mundra International Container Terminal (MICT),Mundra International Container Terminal (MICT),Mundra Port,Mundra Port,22.7382,69.7065,Mundra,22.7382,69.7065
1326,Port,Nhava Sheva Distribution Terminal (NSDT),NSDT NHAVA SHEVA,JNPA Port,JNPA Port,18.9186,72.9692,JNPA,18.9186,72.9692
1327,Port,Nhava Sheva Freeport Terminal (NSFT),Nhava Sheva Freeport Terminal (NSFT),JNPA Port,JNPA Port,18.9186,72.9692,JNPA,18.9186,72.9692
1328,Port,Nhava Sheva India Gateway Terminal (NSIGT),Nhava Sheva India Gateway Terminal (NSIGT),JNPA Port,JNPA Port,18.9186,72.9692,JNPA,18.9186,72.9692
1329,Port,Nhava Sheva International Container Terminal (...,Nhava Sheva International Container Terminal (...,JNPA Port,JNPA Port,18.9186,72.9692,JNPA,18.9186,72.9692
1405,Port,Paradip International Cargo Terminal,Paradip International Cargo Terminal,Paradip Port,Paradip Port,20.2700,86.6700,Paradip,20.2700,86.6700
1463,Port,Pipavav Port,Pipavav Port,Pipavav Port,Pipavav Port,20.9300,71.4900,Pipavav,20.9300,71.4900
1765,Port,Syama Prasad Mookerjee Port Kolkata (SMP Kolkata),Syama Prasad Mookerjee Port Kolkata (SMP Kolkata),Kolkata Port,Kolkata Port,22.5400,88.3100,Kolkata,22.5400,88.3100
1930,Port,Visakha Container Terminal,Visakha Container Terminal,Visakhapatnam Port,Visakhapatnam Port,17.6900,83.3000,Visakhapatnam,17.6900,83.3000


Observation


• The Station Master contains 22 duplicate Location Code records.
• All duplicate records correspond to the generic Location Code "Port".
• These records represent different JNPT port terminals rather than data quality issues.
• Since the origin terminal is already identified from the source movement file,
•these duplicate 'Port' records do not affect OD pair construction.

**STEP 7  Merge Movement with Station Master**

In [78]:
station_lookup = station_df[
    ["Location Code", "Division (Normalized)"]
].rename(columns={"Location Code": "location_code"})

In [79]:
# Merge only the normalized railway division into movement_data

movement_df = movement_df.merge(
    station_lookup,
    on="location_code",
    how="left"
)

In [80]:
movement_df

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal,journey_key,event_date,event_hour,day_of_week,week_number,Division (Normalized)
0,ABEU2601043,107063052,IMPORT,RAIL,JNPA,Gateway Terminals India (GTI),PORT OUT,2025-12-02 06:20:00,1,18.87029,73.00640,GTI,ABEU2601043_107063052,2025-12-02,6,Tuesday,49,JNPA Port
1,ABEU2601043,107063052,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-02 12:56:00,2,18.99092,73.12000,GTI,ABEU2601043_107063052,2025-12-02,12,Tuesday,49,Mumbai Division
2,ABEU2601043,107063052,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-02 13:12:00,3,19.04000,73.11495,GTI,ABEU2601043_107063052,2025-12-02,13,Tuesday,49,Mumbai Division
3,ABEU2601043,107063052,IMPORT,RAIL,NVRD,NAVADE ROAD Mumbai Railway Division,STATION CROSSED,2025-12-02 13:38:00,4,19.05239,73.10000,GTI,ABEU2601043_107063052,2025-12-02,13,Tuesday,49,Mumbai Division
4,ABEU2601043,107063052,IMPORT,RAIL,DDCL,DOMVIVALI CONTROL CABIN Mumbai Railway Division,STATION CROSSED,2025-12-02 15:10:00,5,19.15260,73.09170,GTI,ABEU2601043_107063052,2025-12-02,15,Tuesday,49,Mumbai Division
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797125,WHSU8451882,107040369,IMPORT,RAIL,KIM,KIM Vadodara Railway Division,STATION CROSSED,2025-11-30 20:00:00,22,21.40000,72.93000,NSIGT,WHSU8451882_107040369,2025-11-30,20,Sunday,48,Vadodara Division
797126,WHSU8451882,107040369,IMPORT,RAIL,AKV,Ankleshwar Jn. Vadodara Division,STATION CROSSED,2025-11-30 22:46:00,23,21.62000,73.00000,NSIGT,WHSU8451882_107040369,2025-11-30,22,Sunday,48,Vadodara Division
797127,WHSU8451882,107040369,IMPORT,RAIL,CCTA,CONCOR CONTAINER TERMINAL ANKLESHWAR Vadodara ...,STATION CROSSED,2025-12-01 19:05:00,24,21.61980,73.03770,NSIGT,WHSU8451882_107040369,2025-12-01,19,Monday,49,Vadodara Division
797128,WHSU8451882,107040369,IMPORT,RAIL,AKV,Ankleshwar Jn. Vadodara Division,STATION CROSSED,2025-12-02 02:16:00,25,21.62000,73.00000,NSIGT,WHSU8451882_107040369,2025-12-02,2,Tuesday,49,Vadodara Division
797129,WHSU8451882,107040369,IMPORT,RAIL,CCTA,CONCOR CONTAINER TERMINAL ANKLESHWAR Vadodara ...,STATION CROSSED,2025-12-02 02:20:00,26,21.61980,73.03770,NSIGT,WHSU8451882_107040369,2025-12-02,2,Tuesday,49,Vadodara Division

In [81]:
movement_df.columns.to_list()

['cntr_no',
 'cntr_trxn_id',
 'category',
 'transport_mode',
 'location_code',
 'location_name',
 'event_name',
 'event_time',
 'station_sequence',
 'Latitude',
 'Longitude',
 'terminal',
 'journey_key',
 'event_date',
 'event_hour',
 'day_of_week',
 'week_number',
 'Division (Normalized)']

In [82]:
# Drop the duplicate column
#movement_df.drop(columns=["Division (Normalized)_y"], inplace=True)

# Rename the remaining column
#movement_df.rename(
 #   columns={"Division (Normalized)_x": "Division (Normalized)"},
  #  inplace=True
#)

In [83]:
print("Movement Shape :", movement_df.shape)

Movement Shape : (797130, 18)

In [84]:
print(
    "Missing Division :",
    movement_df["Division (Normalized)"].isna().sum()
)

Missing Division : 0

In [85]:
movement_df.head()

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal,journey_key,event_date,event_hour,day_of_week,week_number,Division (Normalized)
0,ABEU2601043,107063052,IMPORT,RAIL,JNPA,Gateway Terminals India (GTI),PORT OUT,2025-12-02 06:20:00,1,18.87029,73.00640,GTI,ABEU2601043_107063052,2025-12-02,6,Tuesday,49,JNPA Port
1,ABEU2601043,107063052,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-02 12:56:00,2,18.99092,73.12000,GTI,ABEU2601043_107063052,2025-12-02,12,Tuesday,49,Mumbai Division
2,ABEU2601043,107063052,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-02 13:12:00,3,19.04000,73.11495,GTI,ABEU2601043_107063052,2025-12-02,13,Tuesday,49,Mumbai Division
3,ABEU2601043,107063052,IMPORT,RAIL,NVRD,NAVADE ROAD Mumbai Railway Division,STATION CROSSED,2025-12-02 13:38:00,4,19.05239,73.10000,GTI,ABEU2601043_107063052,2025-12-02,13,Tuesday,49,Mumbai Division
4,ABEU2601043,107063052,IMPORT,RAIL,DDCL,DOMVIVALI CONTROL CABIN Mumbai Railway Division,STATION CROSSED,2025-12-02 15:10:00,5,19.15260,73.09170,GTI,ABEU2601043_107063052,2025-12-02,15,Tuesday,49,Mumbai Division

In [86]:
movement_df["terminal"]

0           GTI
1           GTI
2           GTI
3           GTI
4           GTI
          ...
797125    NSIGT
797126    NSIGT
797127    NSIGT
797128    NSIGT
797129    NSIGT
Name: terminal, Length: 797130, dtype: str


Observation

Successfully enriched the movement dataset using the Station Master.\
All movement records were matched successfully using Location Code.

**STEP 8 : OD Pair Construction**

In [87]:

# Sort Movement Data


movement_df = movement_df.sort_values(by=["journey_key", "station_sequence"]).reset_index(drop=True)

In [88]:

#  Extract Origin Records


origin_df = (movement_df.groupby("journey_key", as_index=False).first())

In [89]:
# extract destination records


destination_df = (
    movement_df
    .groupby("journey_key", as_index=False)
    .last()
)

In [90]:
print("Origin Shape      :", origin_df.shape)
print("Destination Shape :", destination_df.shape)

Origin Shape      : (27047, 18)
Destination Shape : (27047, 18)

In [91]:

# Create Fact_OD Table


fact_od = pd.DataFrame()

# Journey Information
fact_od["journey_key"] = origin_df["journey_key"]
fact_od["cntr_no"] = origin_df["cntr_no"]
fact_od["cntr_trxn_id"] = origin_df["cntr_trxn_id"]
fact_od["origin"] = origin_df["terminal"]

# Origin Details
fact_od["start_time"] = origin_df["event_time"]

# Destination Details
fact_od["destination_code"] = destination_df["location_code"]
fact_od["destination_name"] = destination_df["location_name"]
fact_od["destination_division"] = destination_df["Division (Normalized)"]
fact_od["end_time"] = destination_df["event_time"]

In [92]:

#  Journey Time
fact_od["journey_hours"] = round(((fact_od["end_time"] - fact_od["start_time"]).dt.total_seconds() / 3600),2)

In [93]:

# Intermediate Stations

fact_od["intermediate_stations"] = (
    destination_df["station_sequence"] - 1
)

In [94]:
fact_od.head()

,journey_key,cntr_no,cntr_trxn_id,origin,start_time,destination_code,destination_name,destination_division,end_time,journey_hours,intermediate_stations
0,AAIU2002386_107048781,AAIU2002386,107048781,BMCT,2025-12-02 02:50:00,MKPP,M/S KANPUR LOGISTICS PARK PRIVATE LIMITED Alla...,Allahabad Division,2025-12-07 10:25:00,127.58,50
1,AAIU2002534_107887564,AAIU2002534,107887564,BMCT,2025-12-25 03:40:00,CSTN,SANAT NAGAR CONCOR SIDING Secunderabad division,Secunderabad Division,2025-12-29 01:05:00,93.42,72
2,AAIU2027077_107047486,AAIU2027077,107047486,BMCT,2025-11-30 12:47:00,MKPP,M/S KANPUR LOGISTICS PARK PRIVATE LIMITED Alla...,Allahabad Division,2025-12-06 05:30:00,136.72,36
3,AAIU2036042_107049922,AAIU2036042,107049922,BMCT,2025-11-30 19:10:00,PHD,Phaphund Allahabad Division,Allahabad Division,2025-12-04 12:54:00,89.73,61
4,AAIU3639398_107047074,AAIU3639398,107047074,BMCT,2025-12-04 06:02:00,MKPP,M/S KANPUR LOGISTICS PARK PRIVATE LIMITED Alla...,Allahabad Division,2025-12-09 21:30:00,135.47,36

**STEP 9 : Create OD Summary**

In [1]:
# od summary created

od_summary = (
    fact_od.groupby( ["origin", "destination_division"], as_index=False).agg(
        container_count=("cntr_trxn_id", "nunique"),
        average_journey_time=("journey_hours", "mean"),
        average_intermediate_stations=("intermediate_stations", "mean")))

NameError: name 'fact_od' is not defined

In [96]:
od_summary

,origin,destination_division,container_count,average_journey_time,average_intermediate_stations
0,BMCT,Agra Division,34,64.221765,49.088235
1,BMCT,Ahmedabad Division,48,777.538750,35.687500
2,BMCT,Ajmer Division,1,473.980000,4.000000
3,BMCT,Allahabad Division,864,104.494527,36.397229
4,BMCT,Amritsar Division,24,152.876667,28.541667
...,...,...,...,...,...
102,NSIGT,Nagpur Division,204,78.371127,69.705882
103,NSIGT,Nanded Division,31,27.289677,23.806452
104,NSIGT,Ratlam Division,129,40.211938,27.767442
105,NSIGT,Secunderabad Division,264,103.690226,58.400000
106,NSIGT,Vadodara Division,148,58.368649,19.459459

STEP 11: LEG_TABLE

In [97]:
# Sort movement data by journey and station sequence
movement_data = movement_df.sort_values(
    by=["journey_key", "station_sequence"]
).reset_index(drop=True)

In [98]:
movement_df

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal,journey_key,event_date,event_hour,day_of_week,week_number,Division (Normalized)
0,AAIU2002386,107048781,IMPORT,RAIL,JNPA,Bharat Mumbai Container Terminals (PSA),PORT OUT,2025-12-02 02:50:00,1,18.87029,73.00640,BMCT,AAIU2002386_107048781,2025-12-02,2,Tuesday,49,JNPA Port
1,AAIU2002386,107048781,IMPORT,RAIL,JNPT,Jawahar Lal Nehru Port Mumbai Division,STATION CROSSED,2025-12-02 21:00:00,2,18.94590,72.99870,BMCT,AAIU2002386_107048781,2025-12-02,21,Tuesday,49,Mumbai Division
2,AAIU2002386,107048781,IMPORT,RAIL,JSLE,Jasaichirle Jn. Mumbai Division,STATION CROSSED,2025-12-02 23:45:00,3,19.15260,73.09170,BMCT,AAIU2002386_107048781,2025-12-02,23,Tuesday,49,Mumbai Division
3,AAIU2002386,107048781,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-03 00:45:00,4,18.99092,73.12000,BMCT,AAIU2002386_107048781,2025-12-03,0,Wednesday,49,Mumbai Division
4,AAIU2002386,107048781,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-03 01:08:00,5,19.04000,73.11495,BMCT,AAIU2002386_107048781,2025-12-03,1,Wednesday,49,Mumbai Division
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797125,ZXJU0837382,107295943,IMPORT,RAIL,BOK,BORKHEDI Nagpur Railway Division,STATION CROSSED,2025-12-04 14:13:00,85,20.86018,78.97445,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,Nagpur Division
797126,ZXJU0837382,107295943,IMPORT,RAIL,BTBR,Buti Bori Jn. Nagpur Division,STATION CROSSED,2025-12-04 14:20:00,86,20.92000,79.01000,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,Nagpur Division
797127,ZXJU0837382,107295943,IMPORT,RAIL,GMG,GUMGAON Nagpur Railway Division,STATION CROSSED,2025-12-04 14:29:00,87,20.99360,79.03000,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,Nagpur Division
797128,ZXJU0837382,107295943,IMPORT,RAIL,KRI,KHAPRI Nagpur Railway Division,STATION CROSSED,2025-12-04 14:40:00,88,21.05000,79.05000,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,Nagpur Division
797129,ZXJU0837382,107295943,IMPORT,RAIL,PCPK,MULTI MODEL LOGISTIC PARK,STATION CROSSED,2025-12-04 14:56:00,89,28.44920,76.97180,BMCT,ZXJU0837382_107295943,2025-12-04,14,Thursday,49,Nagpur Division

In [99]:
fact_od

,journey_key,cntr_no,cntr_trxn_id,origin,start_time,destination_code,destination_name,destination_division,end_time,journey_hours,intermediate_stations
0,AAIU2002386_107048781,AAIU2002386,107048781,BMCT,2025-12-02 02:50:00,MKPP,M/S KANPUR LOGISTICS PARK PRIVATE LIMITED Alla...,Allahabad Division,2025-12-07 10:25:00,127.58,50
1,AAIU2002534_107887564,AAIU2002534,107887564,BMCT,2025-12-25 03:40:00,CSTN,SANAT NAGAR CONCOR SIDING Secunderabad division,Secunderabad Division,2025-12-29 01:05:00,93.42,72
2,AAIU2027077_107047486,AAIU2027077,107047486,BMCT,2025-11-30 12:47:00,MKPP,M/S KANPUR LOGISTICS PARK PRIVATE LIMITED Alla...,Allahabad Division,2025-12-06 05:30:00,136.72,36
3,AAIU2036042_107049922,AAIU2036042,107049922,BMCT,2025-11-30 19:10:00,PHD,Phaphund Allahabad Division,Allahabad Division,2025-12-04 12:54:00,89.73,61
4,AAIU3639398_107047074,AAIU3639398,107047074,BMCT,2025-12-04 06:02:00,MKPP,M/S KANPUR LOGISTICS PARK PRIVATE LIMITED Alla...,Allahabad Division,2025-12-09 21:30:00,135.47,36
...,...,...,...,...,...,...,...,...,...,...,...
27042,ZIMU3169578_107181580,ZIMU3169578,107181580,BMCT,2025-12-02 12:10:00,PHD,Phaphund Allahabad Division,Allahabad Division,2025-12-06 05:54:00,89.73,61
27043,ZIMU3178083_107388472,ZIMU3178083,107388472,BMCT,2025-12-10 01:47:00,MKPP,M/S KANPUR LOGISTICS PARK PRIVATE LIMITED Alla...,Allahabad Division,2025-12-13 09:00:00,79.22,50
27044,ZWFU1002377_108186820,ZWFU1002377,108186820,GTI,2025-12-23 17:13:00,DCCS,DAULATABAD CONCOR SIDING Nanded division,Nanded Division,2025-12-25 04:40:00,35.45,40
27045,ZXJU0835262_107297151,ZXJU0835262,107297151,BMCT,2025-12-01 05:23:00,JNPT,Jawahar Lal Nehru Port Mumbai Division,Mumbai Division,2026-01-07 01:20:00,883.95,52
27046,ZXJU0837382_107295943,ZXJU0837382,107295943,BMCT,2025-12-02 03:28:00,PCPK,MULTI MODEL LOGISTIC PARK,Nagpur Division,2025-12-04 14:56:00,59.47,88

In [100]:
route_df = fact_od[
    (fact_od["origin"] == "BMCT") &
    (fact_od["destination_division"] == "Secunderabad Division")
].copy()

In [101]:
journey_keys = route_df["journey_key"].unique()

In [102]:
journey_keys

<ArrowStringArray>
['AAIU2002534_107887564', 'ANBU0289724_107724623', 'ANBU1347254_107719691',
 'ANBU5912654_107722704', 'ANBU6591689_107724593', 'ANBU6613927_107716900',
 'ANBU6776398_107720226', 'ANBU6785238_107718839', 'ANBU9241828_107716564',
 'ANBU9279363_107733128',
 ...
 'WBPU2003490_107690320', 'WBPU2004224_107701659', 'WHLU2836758_107058263',
 'WHSU5907861_107252178', 'WHSU6012045_107117662', 'WHSU6079776_107114461',
 'WHSU6477404_107112159', 'XYLU8235141_107341032', 'ZIMU1110056_108221728',
 'ZIMU1369057_108223277']
Length: 485, dtype: str

In [103]:
route_movement = movement_df[
    movement_df["journey_key"].isin(journey_keys)
].copy()

In [104]:
route_movement

,cntr_no,cntr_trxn_id,category,transport_mode,location_code,location_name,event_name,event_time,station_sequence,Latitude,Longitude,terminal,journey_key,event_date,event_hour,day_of_week,week_number,Division (Normalized)
51,AAIU2002534,107887564,IMPORT,RAIL,JNPA,Bharat Mumbai Container Terminals (PSA),PORT OUT,2025-12-25 03:40:00,1,18.87029,73.00640,BMCT,AAIU2002534_107887564,2025-12-25,3,Thursday,52,JNPA Port
52,AAIU2002534,107887564,IMPORT,RAIL,JNPT,Jawahar Lal Nehru Port Mumbai Division,STATION CROSSED,2025-12-26 01:40:00,2,18.94590,72.99870,BMCT,AAIU2002534_107887564,2025-12-26,1,Friday,52,Mumbai Division
53,AAIU2002534,107887564,IMPORT,RAIL,JSLE,Jasaichirle Jn. Mumbai Division,STATION CROSSED,2025-12-26 03:33:00,3,19.15260,73.09170,BMCT,AAIU2002534_107887564,2025-12-26,3,Friday,52,Mumbai Division
54,AAIU2002534,107887564,IMPORT,RAIL,PNVL,Panvel Jn. Mumbai Division,STATION CROSSED,2025-12-26 12:57:00,4,18.99092,73.12000,BMCT,AAIU2002534_107887564,2025-12-26,12,Friday,52,Mumbai Division
55,AAIU2002534,107887564,IMPORT,RAIL,KLMG,KALAMBOLI GOODS Mumbai Railway Division,STATION CROSSED,2025-12-26 14:24:00,5,19.04000,73.11495,BMCT,AAIU2002534_107887564,2025-12-26,14,Friday,52,Mumbai Division
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796215,ZIMU1369057,108223277,IMPORT,RAIL,DUD,DUDHANI Solapur Railway Division,STATION CROSSED,2025-12-26 01:38:00,69,17.36242,76.38000,BMCT,ZIMU1369057_108223277,2025-12-26,1,Friday,52,Solapur Division
796216,ZIMU1369057,108223277,IMPORT,RAIL,WADI,Wadi Jn. Solapur Division,STATION CROSSED,2025-12-26 09:11:00,70,17.05000,76.99155,BMCT,ZIMU1369057_108223277,2025-12-26,9,Friday,52,Solapur Division
796217,ZIMU1369057,108223277,IMPORT,RAIL,VKB,VIKRABAD JN. Secunderabad division,STATION CROSSED,2025-12-26 20:03:00,71,17.34000,77.90941,BMCT,ZIMU1369057_108223277,2025-12-26,20,Friday,52,Secunderabad Division
796218,ZIMU1369057,108223277,IMPORT,RAIL,SNF,SANAT NAGAR,STATION CROSSED,2025-12-27 07:00:00,72,17.46000,78.44000,BMCT,ZIMU1369057_108223277,2025-12-27,7,Saturday,52,Secunderabad Division
796219,ZIMU1369057,108223277,IMPORT,RAIL,CSTN,SANAT NAGAR CONCOR SIDING Secunderabad division,STATION CROSSED,2025-12-27 07:05:00,73,17.40000,78.40000,BMCT,ZIMU1369057_108223277,2025-12-27,7,Saturday,52,Secunderabad Division

In [105]:
route_movement.columns.to_list()

['cntr_no',
 'cntr_trxn_id',
 'category',
 'transport_mode',
 'location_code',
 'location_name',
 'event_name',
 'event_time',
 'station_sequence',
 'Latitude',
 'Longitude',
 'terminal',
 'journey_key',
 'event_date',
 'event_hour',
 'day_of_week',
 'week_number',
 'Division (Normalized)']

In [106]:
route_movement = route_movement[
    [
        "journey_key",
        "terminal",
        "station_sequence",
        "location_code",
        "location_name",
        "Latitude",
        "Longitude",
        "event_time",
        "Division (Normalized)"
    ]
].copy()

In [107]:
route_movement

,journey_key,terminal,station_sequence,location_code,location_name,Latitude,Longitude,event_time,Division (Normalized)
51,AAIU2002534_107887564,BMCT,1,JNPA,Bharat Mumbai Container Terminals (PSA),18.87029,73.00640,2025-12-25 03:40:00,JNPA Port
52,AAIU2002534_107887564,BMCT,2,JNPT,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,Mumbai Division
53,AAIU2002534_107887564,BMCT,3,JSLE,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,Mumbai Division
54,AAIU2002534_107887564,BMCT,4,PNVL,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,Mumbai Division
55,AAIU2002534_107887564,BMCT,5,KLMG,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,Mumbai Division
...,...,...,...,...,...,...,...,...,...
796215,ZIMU1369057_108223277,BMCT,69,DUD,DUDHANI Solapur Railway Division,17.36242,76.38000,2025-12-26 01:38:00,Solapur Division
796216,ZIMU1369057_108223277,BMCT,70,WADI,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,Solapur Division
796217,ZIMU1369057_108223277,BMCT,71,VKB,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,Secunderabad Division
796218,ZIMU1369057_108223277,BMCT,72,SNF,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,Secunderabad Division
796219,ZIMU1369057_108223277,BMCT,73,CSTN,SANAT NAGAR CONCOR SIDING Secunderabad division,17.40000,78.40000,2025-12-27 07:05:00,Secunderabad Division

In [108]:
route_movement = route_movement.sort_values(
    by=["journey_key", "station_sequence"]
).reset_index(drop=True)

In [109]:
route_movement

,journey_key,terminal,station_sequence,location_code,location_name,Latitude,Longitude,event_time,Division (Normalized)
0,AAIU2002534_107887564,BMCT,1,JNPA,Bharat Mumbai Container Terminals (PSA),18.87029,73.00640,2025-12-25 03:40:00,JNPA Port
1,AAIU2002534_107887564,BMCT,2,JNPT,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,Mumbai Division
2,AAIU2002534_107887564,BMCT,3,JSLE,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,Mumbai Division
3,AAIU2002534_107887564,BMCT,4,PNVL,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,Mumbai Division
4,AAIU2002534_107887564,BMCT,5,KLMG,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,Mumbai Division
...,...,...,...,...,...,...,...,...,...
30706,ZIMU1369057_108223277,BMCT,69,DUD,DUDHANI Solapur Railway Division,17.36242,76.38000,2025-12-26 01:38:00,Solapur Division
30707,ZIMU1369057_108223277,BMCT,70,WADI,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,Solapur Division
30708,ZIMU1369057_108223277,BMCT,71,VKB,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,Secunderabad Division
30709,ZIMU1369057_108223277,BMCT,72,SNF,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,Secunderabad Division
30710,ZIMU1369057_108223277,BMCT,73,CSTN,SANAT NAGAR CONCOR SIDING Secunderabad division,17.40000,78.40000,2025-12-27 07:05:00,Secunderabad Division

In [110]:
# using shift for the od pair
route_movement["to_station"] = route_movement.groupby("journey_key")["location_name"].shift(-1)

route_movement["to_latitude"] = route_movement.groupby("journey_key")["Latitude"].shift(-1)

route_movement["to_longitude"] = route_movement.groupby("journey_key")["Longitude"].shift(-1)

route_movement["to_time"] = route_movement.groupby("journey_key")["event_time"].shift(-1)

route_movement["to_sequence"] = route_movement.groupby("journey_key")["station_sequence"].shift(-1)

In [111]:
route_movement

,journey_key,terminal,station_sequence,location_code,location_name,Latitude,Longitude,event_time,Division (Normalized),to_station,to_latitude,to_longitude,to_time,to_sequence
0,AAIU2002534_107887564,BMCT,1,JNPA,Bharat Mumbai Container Terminals (PSA),18.87029,73.00640,2025-12-25 03:40:00,JNPA Port,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,2.0
1,AAIU2002534_107887564,BMCT,2,JNPT,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,Mumbai Division,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,3.0
2,AAIU2002534_107887564,BMCT,3,JSLE,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,Mumbai Division,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,4.0
3,AAIU2002534_107887564,BMCT,4,PNVL,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,Mumbai Division,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,5.0
4,AAIU2002534_107887564,BMCT,5,KLMG,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,Mumbai Division,NAVADE ROAD Mumbai Railway Division,19.05239,73.10000,2025-12-26 14:29:00,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30706,ZIMU1369057_108223277,BMCT,69,DUD,DUDHANI Solapur Railway Division,17.36242,76.38000,2025-12-26 01:38:00,Solapur Division,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,70.0
30707,ZIMU1369057_108223277,BMCT,70,WADI,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,Solapur Division,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,71.0
30708,ZIMU1369057_108223277,BMCT,71,VKB,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,Secunderabad Division,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,72.0
30709,ZIMU1369057_108223277,BMCT,72,SNF,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,Secunderabad Division,SANAT NAGAR CONCOR SIDING Secunderabad division,17.40000,78.40000,2025-12-27 07:05:00,73.0
30710,ZIMU1369057_108223277,BMCT,73,CSTN,SANAT NAGAR CONCOR SIDING Secunderabad division,17.40000,78.40000,2025-12-27 07:05:00,Secunderabad Division,NaN,NaN,NaN,NaT,NaN

In [112]:
route_movement.rename(columns={
    "location_name": "from_station",
    "Latitude": "from_latitude",
    "Longitude": "from_longitude",
    "event_time": "from_time",
    "station_sequence": "from_sequence"
}, inplace=True)

In [113]:
route_movement = route_movement.dropna().reset_index(drop=True)

In [114]:
route_movement.isnull().sum()

journey_key              0
terminal                 0
from_sequence            0
location_code            0
from_station             0
from_latitude            0
from_longitude           0
from_time                0
Division (Normalized)    0
to_station               0
to_latitude              0
to_longitude             0
to_time                  0
to_sequence              0
dtype: int64

In [115]:
route_movement

,journey_key,terminal,from_sequence,location_code,from_station,from_latitude,from_longitude,from_time,Division (Normalized),to_station,to_latitude,to_longitude,to_time,to_sequence
0,AAIU2002534_107887564,BMCT,1,JNPA,Bharat Mumbai Container Terminals (PSA),18.87029,73.00640,2025-12-25 03:40:00,JNPA Port,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,2.0
1,AAIU2002534_107887564,BMCT,2,JNPT,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,Mumbai Division,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,3.0
2,AAIU2002534_107887564,BMCT,3,JSLE,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,Mumbai Division,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,4.0
3,AAIU2002534_107887564,BMCT,4,PNVL,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,Mumbai Division,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,5.0
4,AAIU2002534_107887564,BMCT,5,KLMG,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,Mumbai Division,NAVADE ROAD Mumbai Railway Division,19.05239,73.10000,2025-12-26 14:29:00,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30221,ZIMU1369057_108223277,BMCT,68,BOT,BOROTI Solapur Railway Division,17.39502,76.25000,2025-12-26 01:25:00,Solapur Division,DUDHANI Solapur Railway Division,17.36242,76.38000,2025-12-26 01:38:00,69.0
30222,ZIMU1369057_108223277,BMCT,69,DUD,DUDHANI Solapur Railway Division,17.36242,76.38000,2025-12-26 01:38:00,Solapur Division,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,70.0
30223,ZIMU1369057_108223277,BMCT,70,WADI,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,Solapur Division,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,71.0
30224,ZIMU1369057_108223277,BMCT,71,VKB,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,Secunderabad Division,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,72.0
30225,ZIMU1369057_108223277,BMCT,72,SNF,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,Secunderabad Division,SANAT NAGAR CONCOR SIDING Secunderabad division,17.40000,78.40000,2025-12-27 07:05:00,73.0

In [116]:
route_movement["time_hours"] =round( (
    route_movement["to_time"] - route_movement["from_time"]
).dt.total_seconds() / 3600,2)

In [117]:
route_movement[
    ["from_station", "to_station", "from_time", "to_time", "time_hours"]
].head()

,from_station,to_station,from_time,to_time,time_hours
0,Bharat Mumbai Container Terminals (PSA),Jawahar Lal Nehru Port Mumbai Division,2025-12-25 03:40:00,2025-12-26 01:40:00,22.00
1,Jawahar Lal Nehru Port Mumbai Division,Jasaichirle Jn. Mumbai Division,2025-12-26 01:40:00,2025-12-26 03:33:00,1.88
2,Jasaichirle Jn. Mumbai Division,Panvel Jn. Mumbai Division,2025-12-26 03:33:00,2025-12-26 12:57:00,9.40
3,Panvel Jn. Mumbai Division,KALAMBOLI GOODS Mumbai Railway Division,2025-12-26 12:57:00,2025-12-26 14:24:00,1.45
4,KALAMBOLI GOODS Mumbai Railway Division,NAVADE ROAD Mumbai Railway Division,2025-12-26 14:24:00,2025-12-26 14:29:00,0.08

In [118]:
# import some library for Haversine formula.
from math import radians, sin, cos, sqrt, atan2

In [119]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in kilometers

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        sin(dlat / 2) ** 2
        + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    )

    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

In [120]:
route_movement["distance_km"] = route_movement.apply(
    lambda x: haversine(
        x["from_latitude"],
        x["from_longitude"],
        x["to_latitude"],
        x["to_longitude"]
    ),
    axis=1
)

In [121]:
# calculate speed
route_movement["speed_kmh"] = (
    route_movement["distance_km"] /
    route_movement["time_hours"]
)

In [122]:
# spped category
def speed_category(speed):
    if speed > 60:
        return "Fast"
    elif speed >= 30:
        return "Moderate"
    else:
        return "Slow"

route_movement["speed_category"] = route_movement["speed_kmh"].apply(speed_category)

In [123]:
route_movement

,journey_key,terminal,from_sequence,location_code,from_station,from_latitude,from_longitude,from_time,Division (Normalized),to_station,to_latitude,to_longitude,to_time,to_sequence,time_hours,distance_km,speed_kmh,speed_category
0,AAIU2002534_107887564,BMCT,1,JNPA,Bharat Mumbai Container Terminals (PSA),18.87029,73.00640,2025-12-25 03:40:00,JNPA Port,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,2.0,22.00,8.446377,0.383926,Slow
1,AAIU2002534_107887564,BMCT,2,JNPT,Jawahar Lal Nehru Port Mumbai Division,18.94590,72.99870,2025-12-26 01:40:00,Mumbai Division,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,3.0,1.88,24.976209,13.285218,Slow
2,AAIU2002534_107887564,BMCT,3,JSLE,Jasaichirle Jn. Mumbai Division,19.15260,73.09170,2025-12-26 03:33:00,Mumbai Division,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,4.0,9.40,18.222336,1.938546,Slow
3,AAIU2002534_107887564,BMCT,4,PNVL,Panvel Jn. Mumbai Division,18.99092,73.12000,2025-12-26 12:57:00,Mumbai Division,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,5.0,1.45,5.483208,3.781523,Slow
4,AAIU2002534_107887564,BMCT,5,KLMG,KALAMBOLI GOODS Mumbai Railway Division,19.04000,73.11495,2025-12-26 14:24:00,Mumbai Division,NAVADE ROAD Mumbai Railway Division,19.05239,73.10000,2025-12-26 14:29:00,6.0,0.08,2.089795,26.122433,Slow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30221,ZIMU1369057_108223277,BMCT,68,BOT,BOROTI Solapur Railway Division,17.39502,76.25000,2025-12-26 01:25:00,Solapur Division,DUDHANI Solapur Railway Division,17.36242,76.38000,2025-12-26 01:38:00,69.0,0.22,14.263778,64.835355,Fast
30222,ZIMU1369057_108223277,BMCT,69,DUD,DUDHANI Solapur Railway Division,17.36242,76.38000,2025-12-26 01:38:00,Solapur Division,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,70.0,7.55,73.663780,9.756792,Slow
30223,ZIMU1369057_108223277,BMCT,70,WADI,Wadi Jn. Solapur Division,17.05000,76.99155,2025-12-26 09:11:00,Solapur Division,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,71.0,10.87,102.693611,9.447434,Slow
30224,ZIMU1369057_108223277,BMCT,71,VKB,VIKRABAD JN. Secunderabad division,17.34000,77.90941,2025-12-26 20:03:00,Secunderabad Division,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,72.0,10.95,57.858762,5.283905,Slow
30225,ZIMU1369057_108223277,BMCT,72,SNF,SANAT NAGAR,17.46000,78.44000,2025-12-27 07:00:00,Secunderabad Division,SANAT NAGAR CONCOR SIDING Secunderabad division,17.40000,78.40000,2025-12-27 07:05:00,73.0,0.08,7.906922,98.836520,Fast

In [124]:
leg_table = route_movement[
    [
        "journey_key",
        "terminal",
        "Division (Normalized)",
        "from_station",
        "to_station",
        "from_latitude",
        "from_longitude",
        "to_latitude",
        "to_longitude",
        "from_time",
        "to_time",
        "distance_km",
        "time_hours",
        "speed_kmh",
        "speed_category"
    ]
].copy()

In [125]:
station_throughput = (
    route_movement.groupby(
        ["from_station", "from_latitude", "from_longitude"],
        as_index=False
    )["journey_key"]
    .nunique()
    .rename(columns={"journey_key": "container_throughput"})
)

In [126]:
station_throughput

,from_station,from_latitude,from_longitude,container_throughput
0,AKALKOT ROAD Solapur Railway Division,17.45000,76.13769,353
1,ALANDI Pune Railway Division,18.45000,74.09310,16
2,AMBALE Pune Railway Division,18.40000,74.17000,16
3,AMBERNATH Mumbai Railway Division,19.21038,73.18000,71
4,ANGAR Solapur Railway Division,17.95000,75.60000,359
...,...,...,...,...
162,WATHAR Pune Railway Division,17.89000,74.14000,16
163,Wadi Jn. Solapur Division,17.05000,76.99155,399
164,YEDSHI Solapur Railway Division,18.31738,75.98000,9
165,YEVAT Pune Railway Division,18.49000,74.26000,368
166,ZAHIRABAD,17.67000,77.61021,86

In [127]:
output_path = r"C:\Users\HP\Desktop\Indian_Railway_Container_Analysis\Data\Prcoessed_data"

In [128]:
print("Rows:", len(fact_od))

print("Unique journey_key:", fact_od["journey_key"].nunique())

print("Unique cntr_no:", fact_od["cntr_no"].nunique())

print("Unique cntr_trxn_id:", fact_od["cntr_trxn_id"].nunique())

Rows: 27047
Unique journey_key: 27047
Unique cntr_no: 27039
Unique cntr_trxn_id: 26711